export const SET_SESSION = 'SET_SESSION';
export const SET_APP_LOADING = 'SET_APP_LOADING';
export const SET_ADD_NOTE_MODAL_VISIBILITY = 'SET_ADD_NOTE_MODAL_VISIBILITY';
export const LOAD_NOTES = 'LOAD_NOTES';
export const ADD_NOTE = 'ADD_NOTE';
export const EDIT_NOTE = 'EDIT_NOTE';
export const UPDATE_NOTE = 'UPDATE_NOTE';
export const DELETE_NOTE = 'DELETE_NOTE';